all:
	g++ test.cpp -o test.exe -DSFML_STATIC -I 
	C:\Users\Jan\Dropbox\cpp\SFML-2.4.2\s\include -L 
	C:\Users\Jan\Dropbox\cpp\SFML-2.4.2\s\lib 
	-lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lwinmm -lgdi32 -lfreetype -ljpeg
